### ISSUE TITLE
AndroidBot.click，getScreenSize等API经常出现响应超时，click方法点击的坐标点也是手机APP上的

### ISSUE THREAD

**Issue by wj45911** [lyousan/android-automate#1]
2024-01-14 21:17:28.776 请求[ f9888dbb-4e25-486f-8fe9-af6e49bd8203 ]发生异常
Exception in thread "main" cn.chci.hmcs.automate.exception.TimeoutException: 响应超时
at cn.chci.hmcs.automate.accessibility.fn.AbstractCommand.send(AbstractCommand.java:82)
at cn.chci.hmcs.automate.accessibility.fn.AbstractCommand.send(AbstractCommand.java:60)
at cn.chci.hmcs.automate.accessibility.fn.Device.getScreenSize(Device.java:22)
at cn.chci.hmcs.automate.core.AndroidBot.getScreenSize(AndroidBot.java:187)

2024-01-15 00:13:49.140 请求[ 88522b81-3fe6-4347-87f7-2ff2f5e95c56 ]发生异常
cn.chci.hmcs.automate.exception.TimeoutException: 响应超时
at cn.chci.hmcs.automate.accessibility.fn.AbstractCommand.send(AbstractCommand.java:82)
at cn.chci.hmcs.automate.accessibility.fn.AbstractCommand.send(AbstractCommand.java:60)
at cn.chci.hmcs.automate.accessibility.fn.Global.click(Global.java:87)
at cn.chci.hmcs.automate.core.AndroidBot.click(AndroidBot.java:163)

**Comment by lyousan** [comment]
响应超时的问题确实存在，但我使用的过程中很少很少发生，如果频繁遇到这样的异常，可能是adb的连接不太稳定。
因公司的设备限制，我一直在安卓8.1的环境下运行，其它版本的测试的很少，而且目前个人开发能力有限，有时候确实会出现一些“奇怪”的问题，api设计上也存在缺陷，包括我自己在业务代码中使用此库时也进行了二次封装，比如包一层try catch来增加一些容错。
```java
public static boolean click(AndroidBot bot, Point point) {
        if (bot == null) {
            return false;
        }
        try {
            return bot.click(point);
        } catch (ServerException e) {
            log.error("", e);
            return false;
        }
    }
// 包一层重试
public static String dump(AndroidBot bot, int retry) {
        String dump = "";
        if (bot == null) {
            return dump;
        }
        retry = Math.max(1, retry);
        while (retry-- > 0) {
            try {
                dump = bot.dump();
                if (!StringUtils.isBlank(dump)) {
                    break;
                }
            } catch (ServerException e) {
                log.error("", e);
            }
        }
        return dump;
    }

**Comment by wj45911** [comment]
嗯嗯，我现在包了一层try catch，dump方法包重试没太明白，这个跟click有关吗？我是在安卓9和鸿蒙3.0都测试过存在这个问题，我是测试抖音进入直播间点用户ID出现弹出层，之后再点击其他空白处是想把这个弹出层关闭，有时候关不了，还有滑动swipe这个api偶尔也是会出现滑不动或者出现超时

**Comment by lyousan** [comment]
dump方法的重试是因为有的时候获取不到布局，可能是某些界面交替的期间，获取到的布局为空就导致解析失败了，在抖音启动的时候就容易出现这个问题，重试一下就能正常获取了。
关于swipe，click这些api有些时候不容易生效，特别是对一些头部app，貌似是能通过某种方法识别出这些点击事件是非用户触发的。
这一套api的优势是能够基于节点进行点击，但也有很多情况下节点不支持点击，这个时候其实用adb的事件会更加稳定，我自己的使用也涉及到抖音，我基本上是通过automate来获取界面的元素，点击滑动这些操作很多都是跟adb混用的。

```java
public static List<String> exec(String command) throws IOException, InterruptedException {
        List<String> list = new ArrayList<>();
        ProcessBuilder pb = new ProcessBuilder(EXECUTOR, EXECUTOR_PARAM, command);
        pb.redirectErrorStream(true);
        Process process = pb.start();
        process.waitFor(20, TimeUnit.SECONDS);
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String len = null;
        while ((len = reader.readLine()) != null) {
            list.add(len);
        }
        reader.close();
        return list;
    }
public static void tap(String udid, int x, int y) {
        try {
            exec("adb -s " + udid + " shell input tap " + x + " " + y);
        } catch (IOException | InterruptedException e) {
            log.error("点击屏幕时发生异常：", e);
        }
    }
public static void swipe(String udid, int x1, int y1, int x2, int y2, long duration) {
        try {
            exec("adb -s " + udid + " shell input swipe " + x1 + " " + y1 + " " + x2 + " " + y2 + " " + duration);
        } catch (IOException | InterruptedException e) {
            log.error("滑动屏幕时发生异常：", e);
        }
    }
```

包括截屏、启动app、关闭app、获取设备信息等很多功能都能够通过adb的方式实现。

**Comment by lyousan** [comment]
我这个项目并不成熟，如果需要更加稳定、完善的自动化解决方案，可以尝试一下[aibote](http://www.aibote.net/technology.html)的rpa，他们提供了web、windows、android三端的自动化接口以及投屏群控等辅助功能，同时也支持更多的语言。
这是他们java版api的仓库 https://github.com/1341191074/aibote4j
他们社群也比较活跃，遇到什么问题都可以直接在群里找到对应API的开发者@1341191074

**Comment by wj45911** [comment]
好的，感谢大佬耐心解答和支持，前面想着加你联系方式，把这个项目搞成熟 ，哈哈哈哈
