### ISSUE TITLE
请教下automate-server，我现在要能支持安卓7，这个需要怎么改？

### ISSUE THREAD

**Issue by wj45911** [lyousan/android-automate#2]
请教下automate-server，我现在要能支持安卓7，这个需要怎么改？

**Comment by lyousan** [comment]
我测试了一下，发现安卓7.0和7.1都有问题，排查日志后发现是由于第三方json库里使用到了java.lang.time这个包下面的类，但是这些内容是在安卓8之后才加入的，将fastjson2换成gson后就正常了，最新的apk已经发布到[v1.4.8](https://github.com/lyousan/android-automate/releases/tag/v1.4.8)

**Comment by wj45911** [comment]
使用你v1.4.8版本，又发现个问题中文会出现乱码，这个本地调测没有问题，automate-client打包成jar，使用Node.input方法中文乱码了

**Comment by lyousan** [comment]
我测试了一下，本地调测、automate-tools工具，以及automate-client打包成jar后都没有出现中文乱码的情况。
测试环境：
安卓7.0，jdk1.8
<img width="1277" alt="联想截图_20240303095024" src="https://github.com/lyousan/android-automate/assets/57056964/630692ca-f470-4edc-8c58-dddbf702fd94">
个人猜测你出现的中文乱码情况可能是由于没有设置-Dfile.encoding=utf8的缘故，当我设置为gbk时，就能稳定出现中文乱码的情况。
尝试如下方式启动jar包
```shell
java -jar -Dfile.encoding=utf8 yourjarfile.jar
```

**Comment by wj45911** [comment]
java -jar -Dfile.encoding=utf8 yourjarfile.jar 设置这个解决了，大佬留个联系方式（微信或者QQ），感谢下你

**Comment by lyousan** [comment]
> java -jar -Dfile.encoding=utf8 yourjarfile.jar 设置这个解决了，大佬留个联系方式（微信或者QQ），感谢下你

vx：zaozaoya9966
